### ISSUE TITLE
How to train new proposals?

### ISSUE THREAD

**Issue by xiaoyongzhu** [mahyarnajibi/SNIPER#10]
Thanks for open sourcing the code, it looks great!

One question I have is how to train new proposals? Since I want to use SNIPER in a very different dataset, I assume the best way for me is to re-calculate the proposals? In that case, how do I re-train the proposal network?

Thanks!

**Comment by mahyarnajibi** [comment]
Hi Xiaoyong,
This feature would be added to the repo in the next couple of days.

**Comment by xiaoyongzhu** [comment]
Thanks! Looking forward!
