### ISSUE TITLE
Inference on multiple images without annotations

### ISSUE THREAD

**Issue by ash1995** [mahyarnajibi/SNIPER#103]
I've read that main_test.py can be used to do inference on multiple images but it seems that you must provide annotations for those images as it looks for instances_{testfolder}.json. Perhaps I'm mistaken but how do you go about doing inference on images without annotations?

**Comment by bharatsingh430** [comment]
You can use the demo file

**Comment by ash1995** [comment]
Isn't the demo file for a single image? 

I used main_test.py with the config I used to train but changed the test set to be named images. But when I ran it, I got this error:

IOError: [Errno 2] No such file or directory: './data/demo_batch/annotations/instances_images.json'

Hence why I thought it requires annotations.

**Comment by hnsywangxin** [comment]
@ash1995
hello,
I also want to detect multiple images now, instead of detecting one single picture like demo.py, I use the for loop to run demo.py, but the time to detect a picture is getting longer and longer, how can I load only one model file to detecting multiple pictures?

**Comment by hnsywangxin** [comment]
@ash1995
@bharatsingh430
hello,
I also want to detect multiple images now, instead of detecting one single picture like demo.py, I use the for loop to run demo.py, but the time to detect a picture is getting longer and longer, how can I load only one model file to detecting multiple pictures?
