### ISSUE TITLE
Avoid image resizing during inference

### ISSUE THREAD

**Issue by xiaoyongzhu** [mahyarnajibi/SNIPER#11]
Hi team,

Another question I have is how to avoid resizing the output image (i.e. output the same image resolution as the input)? One particular example would be for the image below (some random image on Internet), the input resolution is 1023 * 968, however the output resolution is 640 * 480, plus additional white edges. BTW I tried to modify the TEST.SCALES option in the yaml file to a large number but with no luck.
  SCALES:
  - !!python/tuple [1400, 2000]
  - !!python/tuple [1400, 2100]
  - !!python/tuple [1400, 2200]

input:
![image](https://static3.depositphotos.com/1000619/110/i/950/depositphotos_1108767-stock-photo-big-set-of-objects-on.jpg)

output:
![image](https://user-images.githubusercontent.com/1185090/41804812-2454e4d8-765a-11e8-878f-52d4990befb2.png)

**Comment by mahyarnajibi** [comment]
Hi Xiaoyong,
This was a visualization issue. The ```SCALES``` parameter in the config file controls the actual inference scales, not the way final detections are saved as an image. 

This issue is addressed in commit 14f9841. Can you pull the master and try again?

**Comment by xiaoyongzhu** [comment]
It helps! Thanks!

**Comment by jliangqiu** [comment]
@xiaoyongzhu train your new datasets have encounter Image Resize Failed？

**Comment by igygi** [comment]
hi @jliangqiu ,

I am encountering the Image Resize failed problem. were you able to resolve it?
