### ISSUE TITLE
Training on own dataset leads to /train/COCO_train_0000000xxxxxx.jpg error

### ISSUE THREAD

**Issue by igygi** [mahyarnajibi/SNIPER#119]
Hi, I'm trying to train SNIPER on my own dataset. I first ran bash train_neg_props_and_sniper.sh --cfg [PATH_TO_CFG_FILE] as per the instructions in the readme because I was hoping to retrain the proposal network first. However, I run into this error:

AssertionError: Path does not exist: ./data/myowndataset/images/train/COCO_train_000000xxxxxx.jpg

But I am not using coco images but instead my own dataset. Currently, my files are named like this: train_000xxx.jpg. Does this mean I have to rename my files in the the format COCO_train_000000xxxxxx.jpg? Is there any way to let the program automatically accept whatever filename I use?

**Comment by Shawn0Hsu** [comment]
@igygi  Hi, I met the same problem with you. Have you solved the problem?

**Comment by igygi** [comment]
Hi, @Shawn0Hsu , yes I was able to resolve this issue. No need to format your image filenames to adhere to the COCO template. Instead, you can go to SNIPER/lib/dataset/coco.py and edit the 'filename' variable to match your name formatting:

`def image_path_from_index(self, index):
        """ example: images / train2014 / COCO_train2014_000000119993.jpg """
        filename = 'COCO_%s_%012d.jpg' % (self.data_name, index) ### edit this
        image_path = os.path.join(self.data_path, 'images', self.data_name, filename)
        assert os.path.exists(image_path), 'Path does not exist: {}'.format(image_path)
        return image_path`

**Comment by Shawn0Hsu** [comment]
@igygi  thank you!  the method is useful.

**Comment by tdiekel** [comment]
Hey, I'd the same problem. I changed it to use the filename from the annotation file. 

```
def image_path_from_index(self, index):
	""" example: train2014 / Filename_from_ann_file.jpg """
	filename = self.coco.loadImgs(index)[0]['file_name']
	image_path = os.path.join(self.data_path, self.data_name, filename)
	assert os.path.exists(image_path), 'Path does not exist: {}'.format(image_path)
	return image_path
```

**Comment by liangMaxY** [comment]
Hi, I'm trying to train SNIPER on my own dataset，too. I ran bash train_neg_props_and_sniper.sh --cfg [PATH_TO_CFG_FILE] as per the instructions in the readme .but have problems as follow:

AssertionError: rpn data not found at data/computed_proposals/COCO_train2014_rpn.pkl

can you help me
