### ISSUE TITLE
Error when I make SNIPER-mxnet

### ISSUE THREAD

**Issue by Andrea-Chang** [mahyarnajibi/SNIPER#122]
HI. Thanks for this wonderful SNIPER.

I wanted to train SNIPER using my own dataset and to do that I first had to do the installation following the guide you've mentioned.
make -j 8 USE_CUDA_PATH=/usr/local/cuda
but it says that :
![Screenshot from 2019-04-17 14-59-02](https://user-images.githubusercontent.com/12397721/56267894-b4b42d00-6122-11e9-8dc0-50e4c143cb8d.png)

1. configuration:
Ubuntu 18.0.4
CUDA 10.0 with associated cUDNN

2. I'm a mxnet novice. I had install openBLAS, mxnet by using the following command:
sudo apt-get install libopenblas-dev
pip install mxnet-cu100

Kindly help me..
I am stuck on this for very long time.

**Comment by luxedo** [comment]
Did you solved? I'm having the same issue.
