### ISSUE TITLE
bash scripts/compile.sh error

### ISSUE THREAD

**Issue by Andrea-Chang** [mahyarnajibi/SNIPER#123]
Hello, @mahyarnajibi, 
I am new to mxnet and thanks for this wonderful SNIPER.

I have some issue when I compile the SNIPER code.

I successfully compiled SNIPER-mxnet,
(Ubuntu18.04, CUDA10.0, Python2.7, g++/gcc 5.5.0)
But, when I compile: bash scripts/compile.sh
I got the following error msg:

    Compiling NMS module...
    running build_ext
    skipping 'cpu_nms.c' Cython extension (up-to-date)
    building 'cpu_nms' extension
    p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c cpu_nms.c -o build/temp.linux-x86_64-2.7/cpu_nms.o -Wno-cpp -Wno-unused-function
    unable to execute 'p++6': No such file or directory
    error: command 'p++6' failed with exit status 1
    Compiling bbox module...
    running build_ext
    skipping 'bbox.c' Cython extension (up-to-date)
    building 'bbox' extension
    p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o -Wno-cpp -Wno-unused-function
    unable to execute 'p++6': No such file or directory
    error: command 'p++6' failed with exit status 1
    Compiling chips module...
    running build_ext
    skipping 'chips.cpp' Cython extension (up-to-date)
    building 'chips' extension
    p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c chips.cpp -o build/temp.linux-x86_64-2.7/chips.o
    unable to execute 'p++6': No such file or directory
    error: command 'p++6' failed with exit status 1
    Compiling coco api...
    running build_ext
    building '_mask' extension
    p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c _mask.c -o build/temp.linux-x86_64-2.7/_mask.o -Wno-cpp -Wno-unused-function -std=c99
    unable to execute 'p++6': No such file or directory
    error: command 'p++6' failed with exit status 1
    All Done!

why it says that "p++6"?
I grep this keyword in all files, but never found it.
Or am I doing some stupid mistakes?
kindly help me, thanks.

**Comment by Andrea-Chang** [comment]
some stupid mistake, and I fixed it.

**Comment by balabala7776** [comment]
hello,how do you fix this problem?
