### ISSUE TITLE
Compile the provided MXNet fork in the repository have some problem

### ISSUE THREAD

**Issue by liangMaxY** [mahyarnajibi/SNIPER#136]
cd to SNIPER-mxnet，i usemake -j 8 USE_CUDA_PATH=/user/local/cuda-9.0 but have some problem。（cudn、cudnn、OpenBLAS are installed），but opencv use pip  to install in the virtal environment （opencv-python），and mxnet not install，what should i do next ？please ，fresh man。

Makefile:166: "USE_LAPACK disabled because libraries were not found"
Makefile:240: WARNING: Significant performance increases can be achieved by installing and enabling gperftools or jemalloc development packages
Running CUDA_ARCH: -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=[sm_70,compute_70] --fatbin-options -compress-all
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_convolution.cc -o build/src/operator/nn/mkldnn/mkldnn_convolution.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_concat.cc -o build/src/operator/nn/mkldnn/mkldnn_concat.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_act.cc -o build/src/operator/nn/mkldnn/mkldnn_act.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_softmax.cc -o build/src/operator/nn/mkldnn/mkldnn_softmax.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_copy.cc -o build/src/operator/nn/mkldnn/mkldnn_copy.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/mkldnn/mkldnn_fully_connected.cc -o build/src/operator/nn/mkldnn/mkldnn_fully_connected.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/cudnn/cudnn_algoreg.cc -o build/src/operator/nn/cudnn/cudnn_algoreg.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/ -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/dlpack/include -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/user/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/xu/SNIPER/SNIPER-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/nn/cudnn/cudnn_batch_norm.cc -o build/src/operator/nn/cudnn/cudnn_batch_norm.o
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/mkldnn/mkldnn_act.cc:28:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_act.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_act.o] Error 1
make: *** 正在等待未完成的任务....
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/io.h:34,
                 from src/operator/nn/mkldnn/../convolution-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_convolution.cc:26:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/cudnn/./../batch_norm-inl.h:31,
                 from src/operator/nn/cudnn/./cudnn_batch_norm-inl.h:33,
                 from src/operator/nn/cudnn/cudnn_batch_norm.cc:27:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_convolution.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_convolution.o] Error 1
Makefile:392: recipe for target 'build/src/operator/nn/cudnn/cudnn_batch_norm.o' failed
make: *** [build/src/operator/nn/cudnn/cudnn_batch_norm.o] Error 1
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/mkldnn/../fully_connected-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_fully_connected.cc:26:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_fully_connected.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_fully_connected.o] Error 1
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator.h:38,
                 from src/operator/nn/mkldnn/../concat-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_concat.cc:25:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:32,
                 from src/operator/nn/mkldnn/../../mxnet_op.h:30,
                 from src/operator/nn/mkldnn/../softmax-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_softmax.cc:26:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
In file included from /home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:32,
                 from src/operator/nn/mkldnn/../../mxnet_op.h:30,
                 from src/operator/nn/mkldnn/../softmax-inl.h:30,
                 from src/operator/nn/mkldnn/mkldnn_copy.cc:26:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/./base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_concat.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_concat.o] Error 1
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_softmax.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_softmax.o] Error 1
Makefile:392: recipe for target 'build/src/operator/nn/mkldnn/mkldnn_copy.o' failed
make: *** [build/src/operator/nn/mkldnn/mkldnn_copy.o] Error 1
In file included from src/operator/nn/cudnn/./../../../common/cuda_utils.h:31:0,
                 from src/operator/nn/cudnn/./cudnn_algoreg-inl.h:33,
                 from src/operator/nn/cudnn/cudnn_algoreg.cc:26:
/home/xu/SNIPER/SNIPER-mxnet/3rdparty/mshadow/mshadow/base.h:155:23: fatal error: cblas.h: 没有那个文件或目录
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/nn/cudnn/cudnn_algoreg.o' failed
make: *** [build/src/operator/nn/cudnn/cudnn_algoreg.o] Error 1

**Comment by freepoet** [comment]
解决了吗？有没有安装编译步骤的文档啊老哥，球球了
