### ISSUE TITLE
Compile the provided MXNet fork in the repository have some problem 

### ISSUE THREAD

**Issue by liangMaxY** [mahyarnajibi/SNIPER#138]
ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core -llapack -lcudnn  -lcufft -lcuda -lnvrtc -L/usr/local/cuda/lib64/stubs
/usr/bin/ld: warning: libjpeg.so.9, needed by /home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpng16.so.16, needed by /home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libjasper.so.4, needed by /home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_writecmpt’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_interlace_handling@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_IHDR@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_get_io_ptr@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_set_quality@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_quality_scaling@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_encode’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_resync_to_restart@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_decode’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_cleanup’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_longjmp_fn@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_set_defaults@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_gray_to_rgb@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_strtofmt’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_bgr@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_stdio_src@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_finish_compress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_create’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_rgb_to_gray@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_calc_output_dimensions@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_std_error@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_swap@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_destroy_read_struct@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_init’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_palette_to_rgb@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_get_tRNS@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_write_scanlines@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_simple_progression@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_read_header@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_cmprof_createfromclrspc’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_stream_fopen’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_start_compress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_destroy_compress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_packing@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_read_end@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_read_fn@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_write_end@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_matrix_destroy’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_expand_gray_1_2_4_to_8@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_write_fn@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_destroy’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_create_write_struct@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_error@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_destroy_write_struct@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_stdio_dest@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_strip_16@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_stream_close’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_create_read_struct@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_finish_decompress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_readcmpt’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_destroy_decompress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_tRNS_to_alpha@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_CreateDecompress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_alloc_huff_table@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_compression_level@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_CreateCompress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_filter@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_default_qtables@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_init_io@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_getcmptbytype’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_cmprof_destroy’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_get_IHDR@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_start_decompress@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_compression_strategy@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_write_info@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_matrix_create’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jpeg_read_scanlines@LIBJPEG_9.0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_create_info_struct@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_read_update_info@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_write_image@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_read_image@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_read_info@PNG16_0’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘jas_image_chclrspc’未定义的引用
/home/xu/anaconda3/envs/mxnet/lib/libopencv_imgcodecs.so：对‘png_set_strip_alpha@PNG16_0’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:456: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

compile mxnet have problrm，how can i do？

**Comment by satvik007** [comment]
jpeg and png are not installed, or are not on path. 
Type --   whereis libpng 
If not found it means you need to install it and then add to path.

**Comment by liangMaxY** [comment]
@satvik007  thank you！i solve this problem !

**Comment by satvik007** [comment]
@liangMaxY Feel free to close the issues that have been resolved.
