### ISSUE TITLE
main_train.py  CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by scc1012** [mahyarnajibi/SNIPER#14]
when i train use main_train.py, appear the following question.

Optimizer params: {'wd': 0.01, 'lr_scheduler': <train_utils.lr_scheduler.WarmupMultiBatchScheduler object at 0x7fe7702edd90>, 'multi_precision': True, 'learning_rate': 0.00015, 'rescale_grad': 1.0, 'clip_gradient': None, 'momentum': 0.9}
aaa
[00:33:49] /home/czn/scc/SNIPER/SNIPER-mxnet/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
CUDA error: too many resources requested for launch

**Comment by bharatsingh430** [comment]
If you have trouble with memory and the GPU does not have fp16 support, you can turn off half precision and use this model http://data.mxnet.io/models/imagenet/resnet/50-layers/ with the resnet-50 symbol

**Comment by xiaoyongzhu** [comment]
Thanks @bharatsingh430 , my GPU does have fp16 support (it's a V100), but I still have the same issue. Do I need to compile the attached SNIPER-mxnet so it have appropriate fp16 support?

**Comment by bharatsingh430** [comment]
I think if you pull again from master it should be ok. Its not related with fp16 I think.

**Comment by mahyarnajibi** [comment]
Feel free to re-open the issue, if pulling the master branch of *SNIPER*, *SNIPER-mxnet*, and compiling with ```make``` as described in the README does not solve the problem.
