### ISSUE TITLE
train on my data have some problem

### ISSUE THREAD

**Issue by liangMaxY** [mahyarnajibi/SNIPER#140]
/home/xu/anaconda3/envs/mxnet/bin/python3.5 /home/xu/SNIPER/main_train.py
Error in sitecustomize; set PYTHONVERBOSE for traceback:
NameError: name 'modules_list' is not defined
/home/xu/SNIPER/configs/faster/default_configs.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
num_images 9626
COCO_train2014 gt roidb loaded from ./data/cache/COCO_train2014_gt_roidb.pkl
appending ground truth annotations
Reading cached proposals after ***NMS**** from data/proposals/COCO_train2014_rpn_after_nms.pkl
Traceback (most recent call last):
  File "/home/xu/SNIPER/main_train.py", line 72, in <module>
    for image_set in image_sets]
  File "/home/xu/SNIPER/main_train.py", line 72, in <listcomp>
    for image_set in image_sets]
  File "/home/xu/SNIPER/lib/data_utils/load_data.py", line 31, in load_proposal_roidb
    roidb = eval('imdb.' + proposal + '_roidb')(roidb, append_gt,proposal_path=proposal_path)
  File "/home/xu/SNIPER/lib/dataset/imdb.py", line 144, in rpn_roidb
    rpn_roidb = self.load_rpn_roidb(gt_roidb,proposal_path)
  File "/home/xu/SNIPER/lib/dataset/imdb.py", line 132, in load_rpn_roidb
    return self.create_roidb_from_box_list(box_list, mapping_list, gt_roidb)
  File "/home/xu/SNIPER/lib/dataset/imdb.py", line 158, in create_roidb_from_box_list
    assert len(box_list) == self.num_images, 'number of boxes matrix must match number of images'
AssertionError: number of boxes matrix must match number of images
Done!

what problem？ who can help me？

**Comment by aimhabo** [comment]
Would you like to share how did you solve it?

**Comment by freepoet** [comment]
hi,bro! i met same question, do you have solved it? help me plz, thanks!
