### ISSUE TITLE
train on my dataset

### ISSUE THREAD

**Issue by liangMaxY** [mahyarnajibi/SNIPER#141]
**python main_train.py --set TRAIN.USE_NEG_CHIPS False**

/home/xu/new/SNIPER/configs/faster/default_configs.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
num_images 9626
COCO_train2014 gt roidb loaded from /home/xu/new/SNIPER/data/cache/COCO_train2014_gt_roidb.pkl
append flipped images to roidb
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
num_images 1571
COCO_val2014 gt roidb loaded from /home/xu/new/SNIPER/data/cache/COCO_val2014_gt_roidb.pkl
append flipped images to roidb
filtered 0 roidb entries: 22394 -> 22394
add bounding box regression targets
bbox target means:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
bbox target stdevs:
[[0.1 0.1 0.2 0.2]
 [0.1 0.1 0.2 0.2]]
[0.1 0.1 0.2 0.2]
Creating Iterator with 22394 Images
Total number of extracted chips: 28589
Done!
The Iterator has 28592 samples!
Initializing the model...
Optimizer params: {'lr_scheduler': <lib.train_utils.lr_scheduler.WarmupMultiBatchScheduler object at 0x7f311f459828>, 'clip_gradient': None, 'rescale_grad': 1.0, 'multi_precision': True, 'learning_rate': 0.00015, 'momentum': 0.9, 'wd': 0.01}
aaa
[20:04:07] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "main_train.py", line 145, in <module>
    epoch_end_callback=epoch_end_callback, arg_params=arg_params, aux_params=aux_params)
  File "SNIPER-mxnet/python/mxnet/module/base_module.py", line 520, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "SNIPER-mxnet/python/mxnet/module/module.py", line 757, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 616, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "SNIPER-mxnet/python/mxnet/metric.py", line 304, in update_dict
    metric.update_dict(labels, preds)
  File "SNIPER-mxnet/python/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/xu/new/SNIPER/lib/train_utils/metric.py", line 57, in update
    pred_label = mx.ndarray.argmax_channel(pred).asnumpy().astype('int32')
  File "SNIPER-mxnet/python/mxnet/ndarray/ndarray.py", line 1876, in asnumpy
    ctypes.c_size_t(data.size)))
  File "SNIPER-mxnet/python/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
**mxnet.base.MXNetError: [20:04:11] src/storage/./pooled_storage_manager.h:108: cudaMalloc failed: out of memory**

Stack trace returned 10 entries:
[bt] (0) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7f31a0b9f92b]
[bt] (1) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f31a0ba0498]
[bt] (2) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::storage::GPUPooledStorageManager::Alloc(mxnet::Storage::Handle*)+0x154) [0x7f31a35c5c14]
[bt] (3) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::StorageImpl::Alloc(mxnet::Storage::Handle*)+0x5d) [0x7f31a35c7bdd]
[bt] (4) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::NDArray::CheckAndAlloc() const+0x1b1) [0x7f31a0c854b1]
[bt] (5) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::StorageFallbackOpExecutor::PreFCompute(bool)+0x14b5) [0x7f31a3029725]
[bt] (6) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::FComputeExecutor::Run(mxnet::RunContext, bool)+0x19) [0x7f31a302a079]
[bt] (7) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(+0x2fb0f26) [0x7f31a2ff1f26]
[bt] (8) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x8e5) [0x7f31a35a9c15]
[bt] (9) /home/xu/new/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0xeb) [0x7f31a35c046b]

have this problem，how can i solve it？

**Comment by satvik007** [comment]
In config file which is some .yml file in configs/faster.
There is a config  
# Number of images per GPU
  BATCH_IMAGES: 16

Reduce this number depending on your gpu.

**Comment by satvik007** [comment]
https://mxnet.incubator.apache.org/versions/master/faq/env_var.html
As mentioned if we use the parameter '2' then memory requirements may be more than what the workspace threshold so its safer to use '1' for a larger dataset.

**Comment by aimhabo** [comment]
Hi, @satvik007 .

I found that SNIPER organizes image name from [index](https://github.com/mahyarnajibi/SNIPER/blob/714e7399bee1e85854b3895ecaef7b143562eab4/lib/dataset/coco.py#L113), but my image doesn't fellow this rule.

Do you know how to read image from "file_name" of "images" in xxx.json like pytorch's dataloader?
my json file is structure like (and I can confirm that ):
|
|- info{xxx}
|-categories[{id name supercategory}]
|-annotations[
|    |-{category_id bbox area id iscrowd image_id}
|]
|-images[
|    |-{width flickr_url license height id file_name coco_url}
|]

**Comment by satvik007** [comment]
Unfortunately no.
You can load your annotation file using json (in python) and convert it to coco style. Obviously you can change the names of the image files also, just need to keep a mapping so that changes are appropriately made for bbox data. For the data that you might me missing use the one from original coco annotation file.

**Comment by bharatsingh430** [comment]
you can write a new dataset file which parses your input and finally generates a gt_roidb (which is a list of dictionaries)  as is done for pascal or coco

**Comment by liangMaxY** [comment]
@satvik007 ok ，i try  ，it work，thank you for you sharing～

**Comment by liangMaxY** [comment]
@bharatsingh430 i try  satvik007‘s means，and it works ，thank for you share

**Comment by aimhabo** [comment]
@satvik007 but... such as cat_id,all_im_info ... are not the keyword I see in instances_val2014.json. I still don't know how to replace 'image_path_from_index(self, index)' with "images->file_name", the more direct.

**Comment by satvik007** [comment]
@bharatsingh430 Just a non tech question - "What does the acronym - aaa mean?"

**Comment by bharatsingh430** [comment]
I am losing context...just know that it’s some roadside car insurance or battery

**Comment by satvik007** [comment]
@bharatsingh430 

`Initializing the model...
Optimizer params: {'wd': 0.01, 'lr_scheduler': <train_utils.lr_scheduler.WarmupMultiBatchScheduler object at 0x7f70fe38a0d0>, 'multi_precision': True, 'learning_rate': 0.00015, 'rescale_grad': 1.0, 'clip_gradient': None, 'momentum': 0.9} 

aaa`

I meant this "aaa" in the last. Its not important anyways, you can just ignore this.
