### ISSUE TITLE
How many batch does a epoch have? And how offen does it saved?

### ISSUE THREAD

**Issue by aimhabo** [mahyarnajibi/SNIPER#144]
# Number of images per GPU
  BATCH_IMAGES: 8
# Number of images per gpu for each scale
  BATCH_IMAGES:
  - 2
  - 2
  - 4
![Screenshot from 2019-06-17 21-48-20](https://user-images.githubusercontent.com/12708080/59609343-cc6f5800-9149-11e9-9d41-17a5075e54a8.png)

there're 6500 images in the train dataset. Log shows that It'd been trained over 6,700 batches, but still not an epoch.  And there is only a log file in the output, still not any weights-file.
(And strangely, the log has not been updated for an hour.)

![Screenshot from 2019-06-17 21-52-01](https://user-images.githubusercontent.com/12708080/59609540-2bcd6800-914a-11e9-94cd-6d22f930e560.png)

**Comment by aimhabo** [comment]
all right... 2.5w batch -> 1 epoch...

**Comment by ash1995** [comment]
I'm not sure what 2.5w batch means. Could you elaborate?

**Comment by aimhabo** [comment]
@ash1995 It takes 25000 batches as 1 epoch. I don't quite understand why this is the number. I complete 1 epoch in 100 iterations(with 64 batch each iter) in the darknet.

**Comment by ash1995** [comment]
Do you know where this number is set? I can't seem to find 25000 specified in the config file.

**Comment by aimhabo** [comment]
@ash1995 This number is related to the number of pictures in the training set. 
"batches each epoch" should = "training images" / "images each batch"

**Comment by ash1995** [comment]
Oh ok, so NUM_BATCHES = NUM_SAMPLES / BATCH_IMAGES
So in you're case, you have 100544 samples and your number of batches was 25000, so you were using 4 images per GPU.

Got it thanks.

**Comment by aimhabo** [comment]
@ash1995 no... in fact I only train 6000+ samples... so I was surprised when I trained 6500+batches but still didn't save any weights file.
