### ISSUE TITLE
Training with Negative Chip Mining recommend cycle ?

### ISSUE THREAD

**Issue by wxianfeng** [mahyarnajibi/SNIPER#145]
i train SNIPER model with Negative Chip Mining . 

what's num of recommend cycle ? just 2 is ok ? when set to 4,  is better than 2 ?

**Comment by satvik007** [comment]
@wxiafeng Its mentioned in the paper that rpn doesn't have to be very accurate so a short cycle is sufficient.

**Comment by wxianfeng** [comment]
In My experiment

2 is better than 4。 

so i suggest 2, not larger is better。
