### ISSUE TITLE
RuntimeError: Cannot find the MXNet library

### ISSUE THREAD

**Issue by Jimjipeng** [mahyarnajibi/SNIPER#166]
Compile the provided MXNet , success
but ,RuntimeError: Cannot find the MXNet library
List of candidates:
/home/znzx/xjp/SNIPER/SNIPER-mxnet/python/mxnet/libmxnet.so
/home/znzx/xjp/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so
/home/znzx/xjp/SNIPER/SNIPER-mxnet/python/mxnet/../../build/libmxnet.so
../../../libmxnet.so

**Comment by FranciscoReveriano** [comment]
were you able to fix this?
