### ISSUE TITLE
Cannot build mxnet when USE_CUDA=0

### ISSUE THREAD

**Issue by santoshreddy254** [mahyarnajibi/SNIPER#167]
I was not able to build SNIPER-mxnet when disabling CUDA. Following error raises
src/operator/multi_proposal.cc:35:10: fatal error: thrust/sort.h: No such file or directory
 #include <thrust/sort.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:392: recipe for target 'build/src/operator/multi_proposal.o' failed
make: *** [build/src/operator/multi_proposal.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ten1er** [comment]
hi @santoshreddy254 , I met same problem, have you solved it?
