### ISSUE TITLE
KeyError: 'proposal_scores' when FLIP is set to true

### ISSUE THREAD

**Issue by xiaoyongzhu** [mahyarnajibi/SNIPER#17]
when FLIP is set to true, running the repository against coco will produce some error like below:

```
wrote gt roidb to /data/cache/COCO_train2014_gt_roidb.pkl
append flipped images to roidb
Traceback (most recent call last):
  File "main_train.py", line 59, in <module>
    for image_set in image_sets]
  File "lib/data_utils/load_data.py", line 36, in load_proposal_roidb
    roidb = imdb.append_flipped_images(roidb)
  File "lib/dataset/imdb.py", line 249, in append_flipped_images
    'proposal_scores': roidb[i]['proposal_scores']}
KeyError: 'proposal_scores'
```

And changing FLIP to false will eliminate the error. I suspect there's something wrong with the flipping logic (didn't dig deep though).

**Comment by mahyarnajibi** [comment]
Are you using the proposals provided in the repo? Just to make sure can you ```rm data/cache/*``` once and run ```main_train.py``` again?

**Comment by mahyarnajibi** [comment]
Hi @xiaoyongzhu,

Commit 8711340 should address this issue. It also adds the option to remove the need for proposals during training which should be useful for training on new datasets. For this, just pull the```master``` branch and you should be able to train on your new dataset by running ```python main_train.py --set TRAIN.USE_NEG_CHIPS False```.
Option for training on new datasets with negative chip mining would be also added to the ```master``` in the near future.

Hope it helps!

**Comment by xiaoyongzhu** [comment]
Thanks! I will definitely try it out and let you know!

**Comment by xiaoyongzhu** [comment]
It works!
