### ISSUE TITLE
Try on FPN

### ISSUE THREAD

**Issue by Peterwu1994** [mahyarnajibi/SNIPER#19]
Hey, 
Sniper is an awesome work. However ,FPN is a standard component  of object detection for scales with slightly computation increased. Have you tried to combine Sniper with FPN ?

**Comment by bharatsingh430** [comment]
We do combine conv4 and conv5 features and also use deformable convolutions (although predictions are made at only at the combined feature map). After adding features from conv3 and conv2, as done in the original FPN paper, after multi-scale inference, we didn't obtain significant performance gains (although single scale results are better). That being said, newer ways of combining feature-maps like PA-NET could improve performance

**Comment by huangh12** [comment]
Do you mean mAP of SNIP+FPN is inferior to SNIP?

**Comment by bharatsingh430** [comment]
after training faster-rcnn (in the setup I mentioned, without snip) and doing multi-scale inference, I didn't get more than 0.5% improvement with the conv2,conv3 feature maps.

**Comment by bharatsingh430** [comment]
I guess you can try using the FPN symbols from the msra repo (https://github.com/msracver/Deformable-ConvNets) and see if you can get more improvements. In sniper we are only changing the input chips, so it should be possible to take the chips and even train with their (or any other) repo. We will provide chips from our side as well.

**Comment by mahyarnajibi** [comment]
Feel free to re-open the issue if you want to continue the discussion.
