### ISSUE TITLE
mahyarnajibi/SNIPER-mxnet is private or missing

### ISSUE THREAD

**Issue by ytt11** [mahyarnajibi/SNIPER#2]
Thank You for sharing code.
fyi cannot perform git clone --recursive on SNIPER:

_fatal: repository 'https://github.com/mahyarnajibi/SNIPER-mxnet/' not found
fatal: clone of 'https://github.com/mahyarnajibi/SNIPER-mxnet' into submodule path 'SNIPER-mxnet' failed_

**Comment by mahyarnajibi** [comment]
Should be fixed now. Feel free to re-open if the problem continues.
