### ISSUE TITLE
Failed to run the R-FCN 3K demo - nnvm check failed

### ISSUE THREAD

**Issue by Lancelot365** [mahyarnajibi/SNIPER#3]
Hi,

First of all, thanks for providing this nicely organized repo.
I have successfully run SNIPER demo without any problem.
However, for R-FCN 3K, I am not able to run the demo. There is strange error, which originates from asnumpy() function. 
The error message I got is 
SNIPER/CRCNN-mxnet/3rdparty/nnvm/include/nnvm/tuple.h:438: Check failed: dim == static_cast<int>(ndim()) (2 vs. 1) dimension do not match target dimension 2 vs 1

I am using CUDA 9.1 with cuDNN 7.02 on a P3.x16 machine.

I have tried diffrent configures on the cmake, e.g., with/withou mkl, but I still cannot figure out what is the problem.

I can easily convert other NDArray to numpy array without any problem. I just cannot convert the output of the R-FCN network.

Please advise.

**Comment by bharatsingh430** [comment]
We do source python 2_7 mxnet on aws, and compile our mxnet with openblas, please check the makefile in the mxnet repo we have and use it to compile it on aws

**Comment by bharatsingh430** [comment]
i think there was some linking issue to repo, should be fixed now, otherwise mxnet branch should be explicitly changed and cloned.

**Comment by Lancelot365** [comment]
After some research, I found out that this might be related to 
https://github.com/apache/incubator-mxnet/pull/9681
https://cwiki.apache.org/confluence/display/MXNET/Improved+exception+handling+in+MXNet

Inconsistent provide data shape and actual data shape could be the cause.

**Comment by Lancelot365** [comment]
May I know the CUDA and cuDNN version that you are testing on ?
Thanks

**Comment by Lancelot365** [comment]
One of my friends also tried this morning with clean CUDA 9 environment, he got the same error.

**Comment by bharatsingh430** [comment]
we will check it and get back, hard to check these things due to cvpr

**Comment by Lancelot365** [comment]
@bharatsingh430 Sure, Enjoy!

**Comment by Lancelot365** [comment]
@bharatsingh430 @mahyarnajibi 
After some tests, I am pretty sure it is from the MultiProposal OP. I can output relu1 without any problems, but once rois is involved, nnvm will report this checked fail error.

**Comment by bharatsingh430** [comment]
Thanks for the catch. I think we made some last minute merges in the cuda last layers. We will fix it in day or so.

**Comment by bharatsingh430** [comment]
btw, did you use the right mxnet branch for 3k?

**Comment by Lancelot365** [comment]
I have tried all three branches with different build options, no luck with all of them.

**Comment by Lancelot365** [comment]
@bharatsingh430 @mahyarnajibi 
I think I found out the problem.
'im_info'in data has the shape (3,), but in the MultiProposal Op, a 2D tensor is assigned to 'im_info', which causes the problem.
If we reshape the NDArray to (3,1) or (1,3), everything seems to be fine.

There is another small bug, line 119 should be 
`im_info_list.append(one['im_info'])`

**Comment by henrylee2570** [comment]
@Lancelot365 thank you for the catch, the im_info issue has been fixed
