### ISSUE TITLE
Feature request - add docker support

### ISSUE THREAD

**Issue by maksimovkonstantin** [mahyarnajibi/SNIPER#40]

**Comment by halhenke** [comment]
I have a couple of docker images that seem to work pretty well for both the master branch and the R-FCN-3K branch. Im rebuilding them now on CircleCI (takes a couple of hours) and will post links when they are done.

**Comment by halhenke** [comment]
OK - to get the image built for the master branch: `docker pull hal9zillion/sniper-master:demo`

and to use an image built for the 3K branch: `docker pull hal9zillion/sniper-3000:demo`

They arent works of art or anything but i'm using them now and they work for me (actually havent used the master branch one in a bit but i assume it still works).

They are built with CUDA/CUDNN so use `nvidia-docker` if you want to make use of a GPU.

**Comment by maksimovkonstantin** [comment]
@halhenke hi! can you pls share DockerFile for your setup?

**Comment by halhenke** [comment]
Hi @maksimovkonstantin - sure - I'll give the link a little later today - just need to clean a few things up.

**Comment by halhenke** [comment]
Hey @maksimovkonstantin - sorry for delay:

https://github.com/halhenke/docker-sniper

**Comment by maksimovkonstantin** [comment]
@halhenke thanks!
