### ISSUE TITLE
rfcn-3k demo_3k.py result is different with the paper？

### ISSUE THREAD

**Issue by mlinxiang** [mahyarnajibi/SNIPER#42]
![image](https://user-images.githubusercontent.com/6283983/42817598-2acd91ce-8a01-11e8-9919-64baee0913f0.png)
![image](https://user-images.githubusercontent.com/6283983/42817640-3fd31634-8a01-11e8-9caa-4691ff6f229d.png)

**Comment by henrylee2570** [comment]
Hi, we didn’t use SNIPER in the paper, thus model and thresholds etc are not the same as the experiment setup. It’s possible that results are different.

**Comment by mlinxiang** [comment]
i use the cvpr3k branch and download pretrain model, did you mean, the cvpr3k branch is not the implement of "R-FCN-3000 at 30fps: Decoupling Detection and Classification", can share this paper's code, very appreciate for that

**Comment by henrylee2570** [comment]
Hi @mlinxiang , I mean this is a better implementation with SNIPER setup, and gets better result than the original experiment in paper (37.8% vs 34.9% mAP). Output for a single image is certainly possible to be different from that of our old implementation (the visualization results in the paper).

**Comment by mlinxiang** [comment]
in practice i want to test the objectness detector without real object classification，but i didn't find the code and pretrained model, can @henrylee2570 give some help?

**Comment by henrylee2570** [comment]
@mlinxiang  you can get the objectness scores of rois like how it's done in demo.py
https://github.com/mahyarnajibi/SNIPER/blob/f3e1be902c6a8dd957de22f95e6200dd8bee6d71/demo.py#L202
