### ISSUE TITLE
git clone failure

### ISSUE THREAD

**Issue by wujiachen987** [mahyarnajibi/SNIPER#62]
Acconding to readme, I run git clone --recursive https://github.com/mahyarnajibi/SNIPER.git,but i failed.
The error message is as follows:
Submodule path 'SNIPER-mxnet/3rdparty/ps-lite': checked out 'a6dda54604a07d1fb21b016ed1e3f4246b08222a'
Failed to recurse into submodule path 'SNIPER-mxnet/3rdparty/nnvm'
Failed to recurse into submodule path 'SNIPER-mxnet'

I try to run git submodule update --init --recursive, Still can't solve the problem.
The error message is as follows:
fatal: reference is not a tree: fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97
Unable to checkout 'fdba6cc9bd3bec9ccd0592fa3900b7fe25d6cb97' in submodule path 'SNIPER-mxnet/3rdparty/nnvm/tvm'
Failed to recurse into submodule path 'SNIPER-mxnet/3rdparty/nnvm'
Failed to recurse into submodule path 'SNIPER-mxnet'

Thank you for your attention.

**Comment by wujiachen987** [comment]
I think it's because nnvm move to https://github.com/dmlc/tvm/
@mahyarnajibi

**Comment by mahyarnajibi** [comment]
@wujiachen987 
True, the git history tree is changed for that repo. Working on that.

**Comment by mahyarnajibi** [comment]
The issue should be resolved in the latest commit. Can you pull the master and try again?
Thanks

**Comment by wujiachen987** [comment]
I am very sorry to reply now, the problem has been solved. Thank you for your handling.
