### ISSUE TITLE
SNIPER-mxnet core-dumped on Ubuntu 16.04.04

### ISSUE THREAD

**Issue by jwnsu** [mahyarnajibi/SNIPER#9]
Installation and all compilations went smoothly. However, when run "python demo.py", encountered following error:
```
*** invalid %N$ use detected ***
Aborted (core dumped)
```
Further inspection shows a simple test command "import mxnet" gives same error.

Env: ubuntu 16.04.04 (kernel 4.4), CUDA9.0/cudnn 7.0, Nvidia 1080 ti.

Tried another machine with ubuntu 16.04.04 (kernel 4.13) with different CPUs and builds, has exact same error.

Wondering anyone sees same error?

Thanks.

ps: same env runs several mxnet projects without any issue, including Deformable-ConvNet project.

**Comment by jwnsu** [comment]
The issue is gone after change build command to incubator-mxnet instruction from mxnet.apache.org ("make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1"). demo.py also works fine. 

Any reason for this project not to follow incubator-mxnet standard compile command? If there is no particular reason, it's better to use standard incubator-mxnet build command.

Will close this thread after hear a feedback from build question above.

**Comment by bharatsingh430** [comment]
If you paste the multi_proposal* layers from the src/operator/ folder in our mxnet repo into what you have, it should be fine. We will provide the cxx files seperately as well along with the mxnet repo so that these compilation issues can be circumvented.

**Comment by chanajianyu** [comment]
the same problem

**Comment by billhyde** [comment]
@bharatsingh430  By the solution you provide, I solve the core-dumped error, So Cool~ Thank you~
