### ISSUE TITLE
About the grad_scale

### ISSUE THREAD

**Issue by dingjiansw101** [mahyarnajibi/SNIPER#96]
https://github.com/mahyarnajibi/SNIPER/blob/c2ae5a00183c9d38417f780b57fa8492d4024a5b/symbols/faster/resnet_mx_101_e2e.py#L301

First, thanks for sharing your impressive work. I want to know why the grad_scale in bbox_loss is divided by (188 * 16). What does the meaning of number?

**Comment by bharatsingh430** [comment]
128 was probably getting 'nan', so we flipped 12 to 18

**Comment by dingjiansw101** [comment]
I am not very understand what you say. What is the meaning of 188 and 16 in `grad_scale=grad_scale / (188.0*16.0)) `.  Is the number  associated with the number of RoIs?

**Comment by bharatsingh430** [comment]
16 is the batch size, I think this was a last minute change so it hasn't been replaced with the config variable. Although the number of proposals is 300, the number of positives are less, so typically for the regression branch this is set to 128, as done in faster-rcnn or r-fcn.

**Comment by dingjiansw101** [comment]
I see, thank you for your answer.
